"""empty message

Revision ID: 4bb1df079430
Revises: bd475e31458d
Create Date: 2020-05-04 14:56:22.830493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb1df079430'
down_revision = 'bd475e31458d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('probability', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('zone', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zone')
    op.drop_column('user', 'probability')
    # ### end Alembic commands ###
