"""empty message

Revision ID: 9fa04294feb8
Revises: c0165c986437
Create Date: 2020-04-03 19:47:45.243081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa04294feb8'
down_revision = 'c0165c986437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coordnates', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coordnates')
    # ### end Alembic commands ###
