"""empty message

Revision ID: c0165c986437
Revises: a01a75d40ff9
Create Date: 2020-03-07 20:05:33.899848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0165c986437'
down_revision = 'a01a75d40ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pass_img')
    # ### end Alembic commands ###
