"""empty message

Revision ID: ed51ae152adb
Revises: d0cba7192989
Create Date: 2020-05-04 14:48:04.861858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed51ae152adb'
down_revision = 'd0cba7192989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('probability', sa.String(length=512), nullable=False))
    op.add_column('user', sa.Column('zone', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zone')
    op.drop_column('user', 'probability')
    # ### end Alembic commands ###
